metadataId: e46767e4-c6d9-49a6-93e8-716da0922fd7
ogc_feature_api: https://ogcapitest.kartverket.no/rest/services/havnedata3_0/collections
output_directory: produktspesifikasjon
product_slug: havnedata
updated: 2025-01-01
xmi_url: https://sosi.geonorge.no/svn/SOSI/SOSI Del 3/Statens kartverk/Havnedata_testing.xml
